---
abstract: 'Provides a braindead tarball builder thingie'
author:
  - 'Erin Schoenhals <erin@cpanel.net>'
build_requires:
  Test::Simple: '0.44'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-Tar-Builder
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.7_0002
